import {auth,db,storage,functions} from './config.js';
import {collection,doc,getDoc,getDocs,query,where,limit} from 'https://www.gstatic.com/firebasejs/10.12.0/firebase-firestore.js';
import {onAuthStateChanged,createUserWithEmailAndPassword,signInWithEmailAndPassword,signOut,updateProfile,getIdToken} from 'https://www.gstatic.com/firebasejs/10.12.0/firebase-auth.js';
import {httpsCallable} from 'https://www.gstatic.com/firebasejs/10.12.0/firebase-functions.js';
import {ref,uploadBytes,getDownloadURL} from 'https://www.gstatic.com/firebasejs/10.12.0/firebase-storage.js';
import {escapeHTML,extrairValorNumerico} from './utils.js';
const $=id=>document.getElementById(id),call=n=>httpsCallable(functions,n),money=v=>new Intl.NumberFormat('pt-AO',{maximumFractionDigits:2}).format(Number(v||0))+' Kz';let vend=null,produtos=[];
function msg(t,ok=true){$('vendMensagem').textContent=t;$('vendMensagem').className='vend-msg '+(ok?'ok':'err');}
function telas(authOk){$('vendAuth').style.display=authOk?'none':'';$('vendCadastro').style.display='none';$('vendDashboard').style.display=authOk?'block':'none';}
async function carregar(){const u=auth.currentUser;if(!u)return;const s=await getDoc(doc(db,'vendedores',u.uid));if(!s.exists()){telas(true);$('vendDashboard').style.display='none';$('vendCadastro').style.display='block';return}vend={id:s.id,...s.data()};telas(true);render();if(vend.status==='aprovado'&&vend.ativo!==false){try{await getIdToken(u,true)}catch(_){};await Promise.all([carregarProdutos(),carregarPedidos(),carregarDestaques()]);}}
function render(){const nome=vend.nomeLoja||vend.nome||'Minha loja';$('vendNomeLoja').textContent=nome;$('vendLinkLoja').href='loja.html?id='+encodeURIComponent(vend.id);$('vendStatus').textContent=vend.status||'pendente';$('vendSaldo').textContent=money(vend.saldoDisponivel);$('vendVendas').textContent=vend.totalVendas||0;const ok=vend.status==='aprovado'&&vend.ativo!==false;$('vendAviso').textContent=ok?'A sua loja está ativa. Produtos novos precisam de aprovação antes de serem publicados.':'A sua loja ainda precisa de aprovação pela VORA 313.';document.querySelectorAll('[data-aprovado]').forEach(x=>x.style.display=ok?'':'none');}
async function carregarProdutos(){const s=await getDocs(query(collection(db,'produtos'),where('vendedorId','==',auth.currentUser.uid)));produtos=s.docs.map(x=>({id:x.id,...x.data()}));$('vendProdutosCount').textContent=produtos.length;$('vendProdutos').innerHTML=produtos.length?produtos.map(p=>`<div class="vend-item"><div><strong>${escapeHTML(p.nome)}</strong><small>${escapeHTML(p.categoria||'')} · ${money(extrairValorNumerico(p.preco))} · estoque ${p.estoque||0}</small><span>${p.statusAprovacao==='aprovado'?'🟢 Publicado':'🟡 '+escapeHTML(p.statusAprovacao||'aguardando_aprovacao')}</span></div><button data-dest="${escapeHTML(p.id)}">⭐ Destacar</button></div>`).join(''):'<div class="vend-item">Nenhum produto.</div>';}
async function carregarPedidos(){const box=$('vendPedidos');try{const s=await getDocs(query(collection(db,'vendasVendedor'),where('uidVendedor','==',auth.currentUser.uid),limit(50)));box.innerHTML=s.empty?'<div class="vend-item">Nenhum pedido.</div>':s.docs.map(x=>{const p=x.data();return `<div class="vend-item"><div><strong>${escapeHTML(p.codigoRastreio||x.id)}</strong><small>${escapeHTML(p.produtosResumo||'')}</small></div><b>${money(p.valorVendedor)}</b></div>`}).join('')}catch(e){box.textContent='Não foi possível carregar pedidos.';}}
async function carregarDestaques(){const box=$('vendDestaques');try{const s=await getDocs(query(collection(db,'destaquesSolicitados'),where('uidVendedor','==',auth.currentUser.uid),limit(30)));box.innerHTML=s.empty?'<div class="vend-item">Nenhuma solicitação.</div>':s.docs.map(x=>{const d=x.data();return `<div class="vend-item"><div><strong>${escapeHTML(d.nomeProduto||d.produtoId)}</strong><small>${d.dias} dias · ${money(d.valor)}</small></div><span>${escapeHTML(d.status||'pendente')}</span></div>`}).join('')}catch(e){box.textContent='Nenhuma solicitação.';}}
async function cadastro(e){e.preventDefault();const d=Object.fromEntries(new FormData(e.currentTarget));try{const c=await createUserWithEmailAndPassword(auth,d.email,d.senha);await updateProfile(c.user,{displayName:d.nomeLoja});await call('solicitarVendedor')({nome:d.nome,nomeLoja:d.nomeLoja,telefone:d.telefone,email:d.email,morada:d.morada,categoria:d.categoria,descricao:d.descricao});msg('Candidatura enviada. Aguarde a aprovação.');await carregar()}catch(e){msg(e.message||'Erro ao criar conta.',false)}}
async function login(e){e.preventDefault();const d=Object.fromEntries(new FormData(e.currentTarget));try{await signInWithEmailAndPassword(auth,d.email,d.senha);await carregar()}catch(e){msg(e.message||'Erro ao entrar.',false)}}
async function produto(e){e.preventDefault();const f=e.currentTarget,d=Object.fromEntries(new FormData(f));const p={nome:d.nome,categoria:d.categoria,preco:d.preco,precoAntigo:d.precoAntigo,desconto:d.desconto,parcelas:d.parcelas,marca:d.marca,sku:d.sku,tag:d.tag,estoque:Number(d.estoque),descricao:d.descricao,imagens:String(d.imagens||'').split(',').map(x=>x.trim()).filter(Boolean),freteGratis:f.querySelector('[name=freteGratis]').checked};try{if(f.dataset.editId)await call('atualizarProdutoVendedor')({produtoId:f.dataset.editId,produto:p});else await call('criarProdutoVendedor')(p);f.reset();delete f.dataset.editId;msg('Produto enviado para aprovação.');await carregarProdutos()}catch(e){msg(e.message||'Erro ao guardar produto.',false)}}
async function upload(){const input=$('vendImagemUpload');if(!input.files.length)return msg('Selecione uma imagem.',false);try{const urls=[];for(const file of input.files){if(file.size>5*1024*1024)throw Error('Imagem acima de 5 MB.');const r=ref(storage,`vendedores/${auth.currentUser.uid}/produtos/${Date.now()}_${file.name.replace(/[^a-zA-Z0-9._-]/g,'_')}`);await uploadBytes(r,file,{contentType:file.type});urls.push(await getDownloadURL(r))}$('vendImagens').value=[$('vendImagens').value,...urls].filter(Boolean).join(', ');input.value='';msg('Imagens enviadas.')}catch(e){msg(e.message||'Upload falhou.',false)}}
async function destaque(id){const dias=prompt('Digite 7, 15 ou 30 dias:','7');if(!['7','15','30'].includes(dias))return;try{await call('solicitarDestaque')({produtoId:id,dias:Number(dias)});msg('Solicitação enviada. A VORA confirma o pagamento e ativa o destaque.');await carregarDestaques()}catch(e){msg(e.message||'Não foi possível solicitar.',false)}}
async function levantamento(){try{const r=await call('solicitarLevantamento')({});msg(`Levantamento solicitado: ${money(r.data.valor)}. Aguarde análise.`);await carregar()}catch(e){msg(e.message||'Não foi possível solicitar.',false)}}
document.addEventListener('DOMContentLoaded',()=>{ $('formVendedor').addEventListener('submit',cadastro);$('formLoginVendedor').addEventListener('submit',login);$('formProdutoVendedor').addEventListener('submit',produto);$('btnUploadVendedor').addEventListener('click',upload);$('btnLevantamento').addEventListener('click',levantamento);$('btnSairVendedor').addEventListener('click',()=>signOut(auth));$('btnMostrarCadastro').onclick=()=>{telas(false);$('vendAuth').style.display='none';$('vendCadastro').style.display='block'};$('btnMostrarLogin').onclick=()=>{telas(false);$('vendAuth').style.display='block'};document.addEventListener('click',e=>{const b=e.target.closest('[data-dest]');if(b)destaque(b.dataset.dest)});onAuthStateChanged(auth,u=>{if(u)carregar().catch(e=>msg(e.message||'Erro ao carregar.',false));else{telas(false);$('vendCadastro').style.display='none'}})});
