import {auth,db,storage,functions} from './config.js';
import {collection,doc,getDoc,getDocs,query,where,limit} from './supabase-compat.js';
import {onAuthStateChanged,createUserWithEmailAndPassword,signInWithEmailAndPassword,signOut,updateProfile,getIdToken,sendPasswordResetEmail} from './supabase-compat.js';
import {httpsCallable} from './supabase-compat.js';
import {ref,uploadBytes,getDownloadURL} from './supabase-compat.js';
import {escapeHTML,extrairValorNumerico} from './utils.js';
const $=id=>document.getElementById(id),call=n=>httpsCallable(functions,n),money=v=>new Intl.NumberFormat('pt-AO',{maximumFractionDigits:2}).format(Number(v||0))+' Kz';let vend=null,produtos=[];
function msg(t,ok=true){$('vendMensagem').textContent=t;$('vendMensagem').className='vend-msg '+(ok?'ok':'err');}
function telas(authOk){$('vendAuth').style.display=authOk?'none':'';$('vendCadastro').style.display='none';$('vendDashboard').style.display=authOk?'block':'none';}
function prepararCadastroContaAtual(){const u=auth.currentUser;const emailInput=$('vendCadastroEmail');const senhaInput=$('vendCadastroSenha');const aviso=$('vendContaAtual');const trocar=$('btnTrocarConta');if(u?.email&&emailInput){emailInput.value=u.email;emailInput.readOnly=true;emailInput.required=false;senhaInput.value='';senhaInput.style.display='none';senhaInput.required=false;if(aviso){aviso.textContent=`A candidatura será ligada à conta atualmente iniciada: ${u.email}.`;aviso.style.display='block'}if(trocar)trocar.style.display='inline-block';return}if(emailInput){emailInput.readOnly=false;emailInput.required=true}if(senhaInput){senhaInput.style.display='';senhaInput.required=true}if(aviso)aviso.style.display='none';if(trocar)trocar.style.display='none'}
async function carregar(){const u=auth.currentUser;if(!u)return;const s=await getDoc(doc(db,'vendedores',u.id));if(!s.exists()){telas(true);$('vendDashboard').style.display='none';$('vendCadastro').style.display='block';prepararCadastroContaAtual();return}vend={id:s.id,...s.data()};telas(true);render();if(vend.status==='aprovado'&&vend.ativo!==false){try{await getIdToken(u,true)}catch(_){};await Promise.all([carregarProdutos(),carregarPedidos(),carregarDestaques()]);}}
function render(){const nome=vend.nomeLoja||vend.nome||'Minha loja';const u=auth.currentUser;const emailInput=document.querySelector('#vendCadastroEmail');const senhaInput=document.querySelector('#vendCadastroSenha');if(emailInput&&u){emailInput.value=u.email||vend.email||'';emailInput.readOnly=true;emailInput.required=false}if(senhaInput&&u){senhaInput.style.display='none';senhaInput.required=false}const pn=$('perfilNome');if(pn)pn.value=vend.nome||'';const pnj=$('perfilNomeLoja');if(pnj)pnj.value=vend.nomeLoja||'';const pt=$('perfilTelefone');if(pt)pt.value=vend.telefone||'';const pm=$('perfilMorada');if(pm)pm.value=vend.morada||'';const pc=$('perfilCategoria');if(pc)pc.value=vend.categoria||'Outros';const pd=$('perfilDescricao');if(pd)pd.value=vend.descricao||'';const dr=vend.dadosRecebimento||{};const metodo=$('vendMetodoRecebimento');if(metodo)metodo.value=dr.metodo||'';const titular=$('vendTitular');if(titular)titular.value=dr.titular||'';const referencia=$('vendReferencia');if(referencia)referencia.value=dr.referencia||'';$('vendNomeLoja').textContent=nome;$('vendLinkLoja').href='loja.html?id='+encodeURIComponent(vend.id);$('vendStatus').textContent=vend.status||'pendente';$('vendSaldo').textContent=money(vend.saldoDisponivel);$('vendVendas').textContent=vend.totalVendas||0;const ok=vend.status==='aprovado'&&vend.ativo!==false;$('vendAviso').textContent=ok?'A sua loja está ativa. Produtos novos precisam de aprovação antes de serem publicados.':'A sua loja ainda precisa de aprovação pela VORA 313.';document.querySelectorAll('[data-aprovado]').forEach(x=>x.style.display=ok?'':'none');}
async function carregarProdutos(){const s=await getDocs(query(collection(db,'produtos'),where('vendedorId','==',auth.currentUser.id)));produtos=s.docs.map(x=>({id:x.id,...x.data()}));$('vendProdutosCount').textContent=produtos.length;$('vendProdutos').innerHTML=produtos.length?produtos.map(p=>`<div class="vend-item"><div><strong>${escapeHTML(p.nome)}</strong><small>${escapeHTML(p.categoria||'')} · ${money(extrairValorNumerico(p.preco))} · estoque ${p.estoque||0}</small><span>${p.statusAprovacao==='aprovado'&&p.ativo===true?'🟢 Publicado':'🟡 '+escapeHTML(p.statusAprovacao||'aguardando_aprovacao')}</span></div><div><button data-edit="${escapeHTML(p.id)}">✏️ Editar</button> ${p.statusAprovacao==='aprovado'&&p.ativo===true?`<button data-dest="${escapeHTML(p.id)}">⭐ Destacar</button>`:''}</div></div>`).join(''):'<div class="vend-item">Nenhum produto.</div>';}
async function carregarPedidos(){const box=$('vendPedidos');try{const s=await getDocs(query(collection(db,'vendasVendedor'),where('uidVendedor','==',auth.currentUser.id),limit(50)));box.innerHTML=s.empty?'<div class="vend-item">Nenhum pedido.</div>':s.docs.map(x=>{const p=x.data();return `<div class="vend-item"><div><strong>${escapeHTML(p.codigoRastreio||x.id)}</strong><small>${escapeHTML(p.produtosResumo||'')}</small></div><b>${money(p.valorVendedor)}</b></div>`}).join('')}catch(e){box.textContent='Não foi possível carregar pedidos.';}}
async function carregarDestaques(){const box=$('vendDestaques');try{const s=await getDocs(query(collection(db,'destaquesSolicitados'),where('uidVendedor','==',auth.currentUser.id),limit(30)));box.innerHTML=s.empty?'<div class="vend-item">Nenhuma solicitação.</div>':s.docs.map(x=>{const d=x.data();return `<div class="vend-item"><div><strong>${escapeHTML(d.nomeProduto||d.produtoId)}</strong><small>${d.dias} dias · ${money(d.valor)}</small></div><span>${escapeHTML(d.status||'pendente')}</span></div>`}).join('')}catch(e){box.textContent='Nenhuma solicitação.';}}
async function cadastro(e){
  e.preventDefault();
  const d=Object.fromEntries(new FormData(e.currentTarget));
  try{
    let u=auth.currentUser;
    if(!u){
      const c=await createUserWithEmailAndPassword(auth,d.email,d.senha);
      u=c.user;
      // Se a confirmação de e-mail estiver ativa, a conta existe mas ainda
      // não há sessão/JWT para criar a candidatura de vendedor.
      if(!c.session){
        const loginEmail=document.querySelector('#formLoginVendedor [name=email]');
        if(loginEmail)loginEmail.value=d.email||'';
        $('btnMostrarLogin')?.click();
        msg('Conta criada. Confirme o e-mail e depois entre para enviar a candidatura.');
        return;
      }
      await updateProfile(u,{displayName:d.nomeLoja});
    }
    if(!u?.id) throw Object.assign(new Error('Não foi possível confirmar a sessão. Entre novamente para enviar a candidatura.'),{code:'unauthenticated'});
    await call('solicitarVendedor')({nome:d.nome,nomeLoja:d.nomeLoja,telefone:d.telefone,email:u.email,morada:d.morada,categoria:d.categoria,descricao:d.descricao});
    msg('Candidatura enviada. Aguarde a aprovação.');
    await carregar();
  }catch(e){
    if(e?.code==='auth/email-already-in-use'){
      const email=$('vendCadastroEmail');
      if(email)email.value=d.email||'';
      $('btnMostrarLogin')?.click();
      const loginEmail=document.querySelector('#formLoginVendedor [name=email]');
      if(loginEmail)loginEmail.value=d.email||'';
      msg('Este email já possui uma conta. Entre na sua conta para continuar a candidatura.',false);
      return;
    }
    msg(e.message||'Não foi possível concluir o cadastro.',false);
  }
}
async function trocarConta(){try{await signOut(auth);$('formVendedor')?.reset();prepararCadastroContaAtual();msg('Sessão terminada. Agora pode usar outro e-mail.')}catch(e){msg(e.message||'Não foi possível trocar de conta.',false)}}
async function login(e){e.preventDefault();const d=Object.fromEntries(new FormData(e.currentTarget));try{await signInWithEmailAndPassword(auth,d.email,d.senha);await carregar()}catch(e){msg(e.message||'Erro ao entrar.',false)}}
async function recuperarSenha(){const input=document.querySelector('#formLoginVendedor [name=email]');const email=input?.value.trim();if(!email)return msg('Digite o seu email para recuperar a palavra-passe.',false);try{await sendPasswordResetEmail(auth,email);msg('Enviámos as instruções de recuperação para o seu email.')}catch(e){msg(e.message||'Não foi possível recuperar a palavra-passe.',false)}}
async function produto(e){e.preventDefault();const f=e.currentTarget,d=Object.fromEntries(new FormData(f));const p={nome:d.nome,categoria:d.categoria,preco:d.preco,precoAntigo:d.precoAntigo,desconto:d.desconto,parcelas:d.parcelas,marca:d.marca,sku:d.sku,tag:d.tag,estoque:Number(d.estoque),descricao:d.descricao,imagens:String(d.imagens||'').split(',').map(x=>x.trim()).filter(Boolean),freteGratis:f.querySelector('[name=freteGratis]').checked};try{if(f.dataset.editId)await call('atualizarProdutoVendedor')({produtoId:f.dataset.editId,produto:p});else await call('criarProdutoVendedor')(p);f.reset();delete f.dataset.editId;$('vendFormProdutoTitulo').textContent='➕ Adicionar produto';msg('Produto enviado para aprovação.');await carregarProdutos()}catch(e){msg(e.message||'Erro ao guardar produto.',false)}}
async function upload(){const input=$('vendImagemUpload');if(!input.files.length)return msg('Selecione uma imagem.',false);try{const urls=[];for(const file of input.files){if(file.size>5*1024*1024)throw Error('Imagem acima de 5 MB.');const r=ref(storage,`vendedores/${auth.currentUser.id}/produtos/${Date.now()}_${file.name.replace(/[^a-zA-Z0-9._-]/g,'_')}`);await uploadBytes(r,file,{contentType:file.type});urls.push(await getDownloadURL(r))}$('vendImagens').value=[$('vendImagens').value,...urls].filter(Boolean).join(', ');input.value='';msg('Imagens enviadas.')}catch(e){msg(e.message||'Upload falhou.',false)}}
function editarProduto(id){const p=produtos.find(x=>String(x.id)===String(id));if(!p)return;const f=$('formProdutoVendedor');for(const [k,v] of Object.entries({nome:p.nome||'',categoria:p.categoria||'eletronicos',preco:p.preco||'',precoAntigo:p.precoAntigo||'',desconto:p.desconto||'',parcelas:p.parcelas||'',marca:p.marca||'',sku:p.sku||'',tag:p.tag||'',estoque:p.estoque??0,descricao:p.descricao||'',imagens:(p.imagens||[]).join(', ')})){const x=f.elements.namedItem(k);if(x)x.value=v}const cb=f.elements.namedItem('freteGratis');if(cb)cb.checked=p.freteGratis===true;f.dataset.editId=p.id;$('vendFormProdutoTitulo').textContent='✏️ Editar produto';window.scrollTo({top:f.getBoundingClientRect().top+window.scrollY-20,behavior:'smooth'});msg('Produto carregado para edição. Ao guardar, voltará para aprovação.')}
async function destaque(id){const dias=prompt('Digite 7, 15 ou 30 dias:','7');if(!['7','15','30'].includes(dias))return;try{await call('solicitarDestaque')({produtoId:id,dias:Number(dias)});msg('Solicitação enviada. A VORA confirma o pagamento e ativa o destaque.');await carregarDestaques()}catch(e){msg(e.message||'Não foi possível solicitar.',false)}}

async function salvarPerfil(e){e.preventDefault();try{const d=Object.fromEntries(new FormData(e.currentTarget));await call('atualizarPerfilVendedor')(d);msg('Perfil da loja atualizado.');await carregar()}catch(e){msg(e.message||'Não foi possível atualizar a loja.',false)}}
async function salvarRecebimento(e){e.preventDefault();try{await call('atualizarDadosRecebimento')({metodo:$('vendMetodoRecebimento').value,titular:$('vendTitular').value,referencia:$('vendReferencia').value});msg('Dados de recebimento guardados com segurança.');await carregar()}catch(e){msg(e.message||'Não foi possível guardar os dados.',false)}}
async function levantamento(){try{const r=await call('solicitarLevantamento')({});msg(`Levantamento solicitado: ${money(r.data.valor)}. Aguarde análise.`);await carregar()}catch(e){msg(e.message||'Não foi possível solicitar.',false)}}
document.addEventListener('DOMContentLoaded',()=>{ $('formVendedor').addEventListener('submit',cadastro);$('formPerfilVendedor')?.addEventListener('submit',salvarPerfil);$('formRecebimento')?.addEventListener('submit',salvarRecebimento);$('btnRecuperarSenha')?.addEventListener('click',recuperarSenha);$('formLoginVendedor').addEventListener('submit',login);$('formProdutoVendedor').addEventListener('submit',produto);$('btnUploadVendedor').addEventListener('click',upload);$('btnLevantamento').addEventListener('click',levantamento);$('btnSairVendedor').addEventListener('click',()=>signOut(auth));$('btnTrocarConta')?.addEventListener('click',trocarConta);$('btnMostrarCadastro').onclick=()=>{telas(false);$('vendAuth').style.display='none';$('vendCadastro').style.display='block';prepararCadastroContaAtual()};$('btnMostrarLogin').onclick=()=>{telas(false);$('vendAuth').style.display='block'};document.addEventListener('click',e=>{const b=e.target.closest('[data-dest]'),ed=e.target.closest('[data-edit]');if(b)destaque(b.dataset.dest);if(ed)editarProduto(ed.dataset.edit)});onAuthStateChanged(auth,u=>{if(u)carregar().catch(e=>msg(e.message||'Erro ao carregar.',false));else{telas(false);$('vendAuth').style.display='none';$('vendCadastro').style.display='block';prepararCadastroContaAtual()}})});
