-- VORA 313 — Favoritos reais por conta
-- Produtos e lojas são guardados separadamente para manter as relações simples,
-- RLS explícita e consultas eficientes no frontend.

create table if not exists public.favoritos_produtos (
  id bigint generated by default as identity primary key,
  uid_cliente uuid not null default auth.uid() references auth.users(id) on delete cascade,
  produto_id text not null references public.produtos(id) on delete cascade,
  criado_em timestamptz not null default now(),
  constraint favoritos_produtos_unicos unique (uid_cliente, produto_id)
);

create index if not exists idx_favoritos_produtos_uid
  on public.favoritos_produtos (uid_cliente, criado_em desc);

create index if not exists idx_favoritos_produtos_produto
  on public.favoritos_produtos (produto_id);

create table if not exists public.favoritos_vendedores (
  id bigint generated by default as identity primary key,
  uid_cliente uuid not null default auth.uid() references auth.users(id) on delete cascade,
  vendedor_id uuid not null references public.vendedores(id) on delete cascade,
  criado_em timestamptz not null default now(),
  constraint favoritos_vendedores_unicos unique (uid_cliente, vendedor_id)
);

create index if not exists idx_favoritos_vendedores_uid
  on public.favoritos_vendedores (uid_cliente, criado_em desc);

create index if not exists idx_favoritos_vendedores_vendedor
  on public.favoritos_vendedores (vendedor_id);

alter table public.favoritos_produtos enable row level security;
alter table public.favoritos_vendedores enable row level security;

-- Cada comprador só pode ler os próprios favoritos.
drop policy if exists favoritos_produtos_select_proprios on public.favoritos_produtos;
create policy favoritos_produtos_select_proprios
  on public.favoritos_produtos
  for select to authenticated
  using (uid_cliente = auth.uid());

-- A identidade do proprietário vem sempre do JWT; nunca do frontend.
drop policy if exists favoritos_produtos_insert_proprios on public.favoritos_produtos;
create policy favoritos_produtos_insert_proprios
  on public.favoritos_produtos
  for insert to authenticated
  with check (uid_cliente = auth.uid());

drop policy if exists favoritos_produtos_delete_proprios on public.favoritos_produtos;
create policy favoritos_produtos_delete_proprios
  on public.favoritos_produtos
  for delete to authenticated
  using (uid_cliente = auth.uid());

drop policy if exists favoritos_vendedores_select_proprios on public.favoritos_vendedores;
create policy favoritos_vendedores_select_proprios
  on public.favoritos_vendedores
  for select to authenticated
  using (uid_cliente = auth.uid());

drop policy if exists favoritos_vendedores_insert_proprios on public.favoritos_vendedores;
create policy favoritos_vendedores_insert_proprios
  on public.favoritos_vendedores
  for insert to authenticated
  with check (uid_cliente = auth.uid());

drop policy if exists favoritos_vendedores_delete_proprios on public.favoritos_vendedores;
create policy favoritos_vendedores_delete_proprios
  on public.favoritos_vendedores
  for delete to authenticated
  using (uid_cliente = auth.uid());

grant select, insert, delete on public.favoritos_produtos to authenticated;
grant select, insert, delete on public.favoritos_vendedores to authenticated;
grant usage, select on sequence public.favoritos_produtos_id_seq to authenticated;
grant usage, select on sequence public.favoritos_vendedores_id_seq to authenticated;

comment on table public.favoritos_produtos is 'Favoritos reais de produtos por comprador autenticado.';
comment on table public.favoritos_vendedores is 'Favoritos reais de lojas/vendedores por comprador autenticado.';
