-- VORA 313 — fluxo de acompanhamento de pedidos e histórico de estados.
-- Não cria novos estados de pedido. Usa exatamente os estados existentes em vendas.
begin;

create table if not exists public.pedido_status_historico (
  id bigint generated by default as identity primary key,
  venda_id text not null references public.vendas(id) on delete restrict,
  status_anterior text,
  status_novo text not null,
  origem text not null default 'sistema'
    check (origem in ('sistema','pagamento','vendedor','administrador')),
  ator_id uuid references auth.users(id) on delete set null,
  detalhes jsonb not null default '{}'::jsonb
    check (jsonb_typeof(detalhes) = 'object'),
  criado_em timestamptz not null default now(),
  constraint pedido_status_historico_status_novo_check
    check (status_novo in ('aguardando_pagamento','pago','em_preparacao','enviado','entregue','cancelado')),
  constraint pedido_status_historico_status_anterior_check
    check (status_anterior is null or status_anterior in ('aguardando_pagamento','pago','em_preparacao','enviado','entregue','cancelado'))
);

create index if not exists idx_pedido_status_historico_venda_data
  on public.pedido_status_historico(venda_id, criado_em desc);
create index if not exists idx_pedido_status_historico_ator_data
  on public.pedido_status_historico(ator_id, criado_em desc)
  where ator_id is not null;

alter table public.pedido_status_historico enable row level security;
revoke all on public.pedido_status_historico from anon;

-- O histórico é somente leitura para as partes autorizadas. Escrita é feita
-- por funções/backend; comprador e vendedor nunca recebem INSERT/UPDATE/DELETE.
drop policy if exists pedido_status_historico_select_autorizado on public.pedido_status_historico;
create policy pedido_status_historico_select_autorizado
on public.pedido_status_historico
for select to authenticated
using (
  exists (
    select 1 from public.vendas v
    where v.id = pedido_status_historico.venda_id
      and v.uid_cliente = auth.uid()
  )
  or public.is_admin()
  or exists (
    select 1
    from public.venda_itens i
    where i.venda_id = pedido_status_historico.venda_id
      and i.vendedor_id = auth.uid()
  )
);

-- Toda mudança efetiva de status já passa pela função central
-- atualizar_estado_pedido(). O trigger cria o histórico dentro da mesma
-- transação, portanto uma mudança não pode ficar sem seu registo.
create or replace function public.registrar_historico_status_pedido()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  v_origem text := 'sistema';
  v_ator uuid := auth.uid();
begin
  if tg_op = 'INSERT' then
    if auth.uid() is not null then
      if public.is_admin() then v_origem := 'administrador';
      elsif public.is_seller() then v_origem := 'vendedor';
      else v_origem := 'sistema';
      end if;
    end if;
    insert into public.pedido_status_historico
      (venda_id, status_anterior, status_novo, origem, ator_id, detalhes)
    values
      (new.id, null, new.status, v_origem, v_ator,
       jsonb_build_object('evento', 'pedido_criado'));
    return new;
  end if;

  if tg_op = 'UPDATE' and old.status is distinct from new.status then
    if auth.uid() is not null then
      if public.is_admin() then v_origem := 'administrador';
      elsif public.is_seller() then v_origem := 'vendedor';
      else v_origem := 'sistema';
      end if;
    elsif new.status = 'pago' then
      v_origem := 'pagamento';
    end if;

    insert into public.pedido_status_historico
      (venda_id, status_anterior, status_novo, origem, ator_id, detalhes)
    values
      (new.id, old.status, new.status, v_origem, v_ator,
       jsonb_build_object('evento', 'estado_alterado'));
  end if;

  return new;
end;
$$;

drop trigger if exists vendas_registrar_historico_status on public.vendas;
create trigger vendas_registrar_historico_status
after insert or update of status on public.vendas
for each row execute procedure public.registrar_historico_status_pedido();

revoke all on function public.registrar_historico_status_pedido() from public, anon, authenticated;
grant execute on function public.registrar_historico_status_pedido() to service_role;

-- A autorização do vendedor acontece no backend. Para não criar estados por
-- item (que a arquitetura atual não possui), só permitimos ao vendedor avançar
-- um pedido global quando TODOS os itens daquele pedido pertencem à sua loja.
create or replace function public.alterar_estado_pedido_autorizado(
  p_codigo text,
  p_novo_status text
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  pedido public.vendas%rowtype;
  uid uuid := auth.uid();
  administrador boolean := false;
  vendedor boolean := false;
begin
  if uid is null or auth.role() <> 'authenticated' then
    raise exception 'Sessão autenticada necessária.' using errcode = '42501';
  end if;

  administrador := public.is_admin();
  vendedor := public.is_seller();

  if not administrador and not vendedor then
    raise exception 'Sem permissão para atualizar pedidos.' using errcode = '42501';
  end if;

  select * into pedido
  from public.vendas
  where codigo_rastreio = upper(trim(p_codigo))
  for update;

  if not found then
    raise exception 'Pedido não encontrado.' using errcode = 'P0002';
  end if;

  if vendedor and not administrador then
    if p_novo_status not in ('em_preparacao','enviado','entregue') then
      raise exception 'O vendedor só pode avançar preparação, envio e entrega.' using errcode = '42501';
    end if;

    if not exists (
      select 1 from public.venda_itens i
      where i.venda_id = pedido.id and i.vendedor_id = uid
    ) then
      raise exception 'Este pedido não pertence à sua loja.' using errcode = '42501';
    end if;

    if exists (
      select 1 from public.venda_itens i
      where i.venda_id = pedido.id
        and i.vendedor_id is distinct from uid
    ) then
      raise exception 'Este pedido tem itens de outra loja e o estado global deve ser supervisionado pela VORA.' using errcode = '42501';
    end if;
  end if;

  return public.atualizar_estado_pedido(upper(trim(p_codigo)), p_novo_status);
end;
$$;

revoke all on function public.alterar_estado_pedido_autorizado(text, text) from public, anon;
grant execute on function public.alterar_estado_pedido_autorizado(text, text) to authenticated;

notify pgrst, 'reload schema';
commit;
